### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by hasufell** [psibi/streamly-bytestring#2]
Afais there is no release on hackage yet. Not sure if the [PR](https://github.com/psibi/streamly-bytestring/pull/1) is blocking it, but the `Array Word8 <-> ByteString` functions are quite handy.

**Comment by psibi** [comment]
Thanks @hasufell ! I'm waiting for @adithyaov to wrap up the remaining updates on that MR. After that,  it would be a good time to make the release.

**Comment by adithyaov** [comment]
I apologize for the delay. I've used a lot of `Internal` modules of Streamly in that [PR](https://github.com/psibi/streamly-bytestring/pull/1). It would be inconvenient for the users to work with broken links on Hackage and hence am waiting for the next minor release of Streamly which fixes that. It will be released soon, probably in the next couple of days.

**Comment by adithyaov** [comment]
@psibi I think once the azure pipelines succeed, you can release this package.

**Comment by psibi** [comment]
Thanks @adithyaov for the nice work. I just released a new version on Hackage.

@adithyaov What is your Hackage username ? I will add you to that package. I have added Harendra to the package. So, even he should be able to add you up.

**Comment by adithyaov** [comment]
Awesome! My username on hackage is `adithyaov`.

**Comment by psibi** [comment]
Added you to the package. Closing the issue as a release has been made.
