### ISSUE TITLE
Strict upper bound on bytestring

### ISSUE THREAD

**Issue by maralorn** [psibi/streamly-bytestring#30]
The build seems to be compatible with bytestring 0.11.4.0.

**Comment by adithyaov** [comment]
I've bumped the version, the next release of bytestring should be compatible with 0.11.4.0. 
If you need to work with the previous version, I can bump the version bounds on hackage.

**Comment by adithyaov** [comment]
Closing this. The latest version of `streamly-bytestring` is compatible with `0.11.4.0`.
