### ISSUE TITLE
Lazy.fromChunks runs effects strictly for strict Monads (e.g. IO)

### ISSUE THREAD

**Issue by hasufell** [psibi/streamly-bytestring#7]
```hs
Lazy.fromChunks $ ((S.fromList [Strict.toArray (C.singleton 'a'), undefined])
  >>= (\x -> liftIO (putStrLn "blah") >> pure x))
```

will print "blah" twice. `fromChunks` uses [S.foldr](https://hackage.haskell.org/package/streamly-0.7.0/docs/Streamly-Prelude.html#v:foldr) under the hood, whose documentation says

> Please avoid using this routine in strict monads like IO unless you need a strict right fold.

I don't know if there is an elegant way to do this, but the only way I see currently is to:

1. clearly document that `fromChunks` is not lazy in its effects for strict monads
2. provide an IO-friendly alternative, something like: `fromChunks' = S.foldrM (\x b -> unsafeInterleaveIO b >>= \b' -> pure $ BSLI.chunk x b') (pure BSLI.Empty) . S.map Strict.fromArray`

**Comment by adithyaov** [comment]
I agree. I'll check and document that `fromChunks` is not lazy for strict monads. (Edit: This statement might be wrong)

Edit: I'll also need to think about whether IO is the real problem.

> provide an IO-friendly alternative, something like: fromChunks' = S.foldrM (\x b -> unsafeInterleaveIO b >>= \b' -> pure $ BSLI.chunk x b') (pure BSLI.Empty) . S.map Strict.fromArray

I'll think about this and get back to you.

**Comment by adithyaov** [comment]
@hasufell I don't think `streamly-bytestring` is the problem. Could you check if you have the problem using `streamly` on the `array-test` branch.

**Comment by hasufell** [comment]
@adithyaov still the same

**Comment by adithyaov** [comment]
@hasufell You were right. I had something else in mind apparently. I'll update the documentation and make an IO friendly version. In case you want to use `fromChunks`, you can make a new type `LazyIO` with a lazy bind.

Something like, 
```
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

newtype LazyIO a = LazyIO { runLazy :: IO a } deriving (Functor, Applicative)

liftToLazy :: IO a -> LazyIO a
liftToLazy = LazyIO

instance Monad LazyIO where
  return = pure
  LazyIO a >>= f = LazyIO (unsafeInterleaveIO a >>= unsafeInterleaveIO . runLazy . f)

-- | Convert a serial stream of 'Array' 'Word8' to a lazy 'ByteString'.
{-# INLINE fromChunksIO #-}
fromChunksIO :: SerialT IO (Array Word8) -> IO ByteString
fromChunksIO str = runLazy (fromChunks (S.hoist liftToLazy str))
```
This is equivalant to what you have defined.

**Comment by adithyaov** [comment]
I'll be updating the test as well. The following will be the definition.
```
testFromChunksLaziness :: Word8 -> IO Word8
testFromChunksLaziness h = do
  lbs <- Lazy.fromChunksIO $ S.fromList (Strict.toArray (BS.singleton h): undefined)
  return $ BSL.head lbs
```
This test fails with the current `fromChunks`.

**Comment by adithyaov** [comment]
Closing this. @hasufell Thanks for pointing this out :-)
